spring.application.name=notification-service
server.port=9060

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSL=false
# Username
spring.datasource.username=postgres
# Password
spring.datasource.password=password
# everytime we run the application the new database will be created and previous will be discarded
spring.jpa.hibernate.ddl-auto=update
#for displaying the queries
spring.jpa.show-sql=true
#for formatting the single line queries
spring.jpa.properties.hibernate.format_sql=true